### PR TITLE
spk infra YAML conversion, definition.yaml supports secrets handling

### LINKED ISSUE #812: `spk infra` should be using YAML files as opposed to JSON files
**As a:**
A developer

**I want:**
`spk infra scaffold` to generate definition in the form of a yaml file and have `spk infra generate` consume yaml files instead of json files.

**So that:**
there is consistency in using yaml files across Fabrikate and Bedrock.

**Describe the solution you'd like:**
- [x] `spk infra scaffold` should produce a `definition.yaml`
- [x] `spk infra generate` should consume `definition.yaml`

**Does this require updates to documentation?:**
Yes

### PR DESCRIPTION
**Pull request by yradsmikham**
This PR includes the following: 
- `spk infra scaffold` generates `definition.yaml` files.
- `spk infra generate` will parse `definition.yaml` files to generate `spk.tfvars` and `backend.tfvars`
- `definition.yaml` supports secrets in the form of `${env:secret_name}` using local environment variables or a .env file.
- `spk infra generate` will now _correctly_ generate environments in *any* directory structure. For example:

```
Example A:
|- discovery-service
    |- definition.yaml
    |- east
        |- definition.yaml

Example A Output:
|- discovery-service-generated
    |- east
        |- spk.tfvars
        |- backend.tfvars
```
```
Example B:
|- discovery-service
    |- east
        |- definition.yaml

Example B Output:
|- discovery-service-generated
    |- east
        |- spk.tfvars
        |- backend.tfvars
```
```
Example C:
|- discovery-service
    |- definition.yaml

Example C Output:
|- discovery-service-generated
    |- spk.tfvars
    |- backend.tfvars
```

Close https://github.com/microsoft/bedrock/issues/812 & https://github.com/microsoft/bedrock/issues/778.

### CODE REVIEW

**Comment by andrebriggs** [comment]
@yradsmikham Let's re-open this once the design doc is settled

**Review by samiyaakhtar — APPROVED** [review]

**Review by edaena — APPROVED** [review]

**Review by NathanielRose — APPROVED** [review]
lgtm - works on linux and windows

**Comment by andrebriggs** [comment]
@yradsmikham @NathanielRose why do we need to hard code a mock yaml file in src/commands/infra/mocks/definition.yaml ?

Also code coverage went down on `generate.ts` after this merge. Let's make sure we are making the incremental improvements

cc @samiyaakhtar @edaena

**Comment by NathanielRose** [comment]
@andrebriggs I can speak to the mock file, This is being used in the generate unit test - https://github.com/CatalystCode/spk/blob/master/src/commands/infra/generate.test.ts we may be able to remove this when the integration test is merged in.

**Comment by yradsmikham** [comment]
@andrebriggs For consistency, we can definitely generate the yaml file upon executing the tests (similar to what we are doing for the scaffold unit test), that will remove the dependency in having a hard coded yaml file.

We'll make this an item to do for the next iteration for `spk infra generate`.

**Pull request merged**
