### PR TITLE
[HOUSEKEEPING] remove eslint-disable for hld reconicle command

### PR DESCRIPTION
**Pull request by dennisseah**
mainly moving functions around to satisfy `no-use-before-define` rule
no changes in logics in this file

related to https://github.com/microsoft/bedrock/issues/1157

### CODE REVIEW

**Review by andrebriggs — APPROVED** [review]
Just noticing how long `reconcile.ts` is 😅

**Review by evanlouie — APPROVED** [review]

**Review by bnookala — COMMENTED** [review]
@dennisseah In the future, I would like for us to track this sort of housekeeping work on the sprint board - please make sure you are linking an issue/opening an issue so that we know it is happening.

**Review by bnookala — CHANGES_REQUESTED** [review]
@dennisseah Please add an issue to github, and add it to the sprint, as that's our process.

**Comment by dennisseah** [comment]
> @dennisseah In the future, I would like for us to track this sort of housekeeping work on the sprint board - please make sure you are linking an issue/opening an issue so that we know it is happening.

sorry I forgot to link to an issue. I checked with Evan about removing the `eslint-disabled` when I have time. And he gave the green light. We have a lot of these after we switch from `tslint` to `eslint`

**Pull request merged**
