### PR TITLE
generate doc for command

### PR DESCRIPTION
**Pull request by dennisseah**
anyone has any ideas on how to generate doc for commands automatically? thanks

### CODE REVIEW

**Comment by andrebriggs** [comment]
@dennisseah you mean when a `<command>.json` file is updated we should regenerate the documentation has a pre-commit step?

**Review by andrebriggs — APPROVED** [review]

**Comment by dennisseah** [comment]
> @dennisseah you mean when a `<command>.json` file is updated we should regenerate the documentation has a pre-commit step?

yes, how to do this in pre-commit hook?

**Comment by evanlouie** [comment]
we use [husky](https://github.com/typicode/husky) for pre-commit hooks. You can add to the `husky.hooks.pre-commit` script it package.json

**Comment by dennisseah** [comment]
> we use [husky](https://github.com/typicode/husky) for pre-commit hooks. You can add to the `husky.hooks.pre-commit` script it package.json

I do not know how to do this. Will reach out to you. thanks

**Review by jmspring — APPROVED** [review]
Content edits will be handled in a separate issue, otherwise LGTM.

**Comment by dennisseah** [comment]
> Content edits will be handled in a separate issue, otherwise LGTM.

@jmspring these are generated content from command json files, people forgot to generate them in previous PRs. And this will never happen again because @evanlouie showed me how to add git pre-commit hook. thanks

**Pull request merged**
