### PR TITLE
Adds version number and message to Bedrock.yaml

### LINKED ISSUE #1082: SPK bedrock.yaml file should be versioned
**As a:**
Developer
**I want:**
The `bedrock.yaml` file should container the version of `spk` that created/or modified it

**So that:**
the `spk` tool can use this metadata for features such as backwards compatibility and debugging 

**Describe the solution you'd like:**
The `bedrock.yaml` file containers a key value pair for spk version number or build number.

Example
<pre>
rings:
  master:
    isDefault: true
services:
  ./:
    displayName: quick-start-app
    helm:
      chart:
        accessTokenVariable: ACCESS_TOKEN_SECRET
        branch: master
        git: 'https://dev.azure.com/abrig/BedrockRocks/_git/quick-start-helm'
        path: quick-start-app/chart
    k8sBackend: quick-start-app-svc
    k8sBackendPort: 80
    middlewares: []
    pathPrefix: ''
    pathPrefixMajorVersion: ''
variableGroups:
  - quick-start-vg
<b>#THIS IS AN AUTOGENERATED VALUE.
version: 0.5.7 </b>
</pre>
 
**Acceptance Criteria:**
I can see what version of `spk` modified or created the `bedrock.yaml` file

**Does this require updates to documentation?:**
No

### PR DESCRIPTION
**Pull request by sarath-p**
Closes https://github.com/microsoft/bedrock/issues/1082

### CODE REVIEW

**Review by dennisseah — COMMENTED** [review]
we have version: "1.0" in many places in test files. So, we have to update all of them whenever version number changes. am I right? Can we get the version by calling the getVersion function to avoid having to update test? Other thing, the getVersion function get the version from package.json every time, can we cache it?

**Comment by sarath-p** [comment]
Regarding "1.0", it is a test data and not dependent on the actual on version number.  We can implement caching but frequency of calling this method is very low since we it is only used in `project init` and setting up pipelines.

**Comment by dennisseah** [comment]
ok. "1.0"  is coming for mocked.

**Review by andrebriggs — APPROVED** [review]
LGTM

**Review by dennisseah — APPROVED** [review]

**Pull request merged**
