### PR TITLE
Fixing ring integrations tests and some improvements

### LINKED ISSUE #1001: Issue in SPK HLD reconcile command in Lifecycle pipeline
**Describe the bug:**

`Unable to get git origin URL.: Error` from 
```
spk hld reconcile fabrikam2019 /home/vsts/fabrikam-hld ./..
info:    Found HLD at /home/vsts/fabrikam-hld
info:    Found Bedrock Application at /home/vsts
info:    Attempting to reconcile HLD with services tracked in bedrock.yaml
info:    Running: cd /home/vsts/fabrikam-hld && mkdir -p fabrikam2019 && fab add fabrikam2019 --path ./fabrikam2019 --method local
time="18-02-2020 03:04:06" level=info msg="💾  Loading component.yaml"
time="18-02-2020 03:04:06" level=info msg="💾  Writing 'component.yaml'"
error:   An error occurred while reconciling HLD
error:   Unable to get git origin URL.: Error
##[error]Bash exited with code '1'.
Finishing: Download Fabrikate and SPK, Update HLD, Push changes, Open PR
```

### PR DESCRIPTION
**Pull request by andrebriggs**
- Added setup for helm chart repo and added new params that now seem to be required for `spk service create` integration test
  - Previously the integration test ran hundreds of times without specifying those params so updating the tests failed to occur
- Added comment sections to read the `validations.sh` more easily
- Updated the pull request approval function in `functions.sh` 
- Fixed an issue in the helm template file used in the integration issues
- Added functionality in `validations.sh` to approve more pull requests generated from pipelines
- Set a variable in `smoke-test-pipeline.yaml` to skip [component governance](https://docs.opensource.microsoft.com/tools/cg/index.html)
  - This means we save 30 seconds to 3 minutes in each parallel test to avoid security scanning that we don't need since we are not publishing anything in these tests

Fixes https://github.com/microsoft/bedrock/issues/1001

### CODE REVIEW

**Review by mtarng — APPROVED** [review]

**Comment by dennisseah** [comment]
i got an error in git cloing helm-chart repo, when running the script (validations.sh). and the script ended with 
`Successfully reached the end of spk deployment get tests.`

```
time="23-02-2020 07:19:59" level=info msg="🚁  Component requested branch 'master'"
time="23-02-2020 07:19:59" level=info msg="🚁  Cloning https://dev.azure.com/veseah/BedrockSPK/_git/fabrikam-helm-charts@master:head => /tmp/3f8eca36-23ab-4d6b-818b-b9b9592342fb"
time="23-02-2020 07:19:59" level=error msg="🚫  Error occurred while cloning: 'https://dev.azure.com/veseah/BedrockSPK/_git/fabrikam-helm-charts@master:head'\nexit status 128: Cloning into '/tmp/3f8eca36-23ab-4d6b-818b-b9b9592342fb'...\nfatal: could not read Username for 'https://dev.azure.com': terminal prompts disabled\n"
Error: exit status 128
```
where should I look?
thanks

**Comment by dennisseah** [comment]
> i got an error in git cloing helm-chart repo, when running the script (validations.sh). and the script ended with
> `Successfully reached the end of spk deployment get tests.`
> 
> ```
> time="23-02-2020 07:19:59" level=info msg="🚁  Component requested branch 'master'"
> time="23-02-2020 07:19:59" level=info msg="🚁  Cloning https://dev.azure.com/veseah/BedrockSPK/_git/fabrikam-helm-charts@master:head => /tmp/3f8eca36-23ab-4d6b-818b-b9b9592342fb"
> time="23-02-2020 07:19:59" level=error msg="🚫  Error occurred while cloning: 'https://dev.azure.com/veseah/BedrockSPK/_git/fabrikam-helm-charts@master:head'\nexit status 128: Cloning into '/tmp/3f8eca36-23ab-4d6b-818b-b9b9592342fb'...\nfatal: could not read Username for 'https://dev.azure.com': terminal prompts disabled\n"
> Error: exit status 128
> ```
> 
> where should I look?
> thanks

Andre helped and figure out that it is a private repo issue

**Review by dennisseah — APPROVED** [review]

**Comment by andrebriggs** [comment]
@dennisseah I created https://github.com/microsoft/bedrock/issues/1025 to track your issue

**Comment by andrebriggs** [comment]
Given the comments in the [bug](https://github.com/microsoft/bedrock/issues/1025#issuecomment-590139787) I want to confirm if this private helm chart issue will be resolved by not creating a separate repo. If so I will push a commit.

**Pull request merged**
