### PR TITLE
Change output shorthand to -o

### PR DESCRIPTION
**Pull request by samiyaakhtar**

### CODE REVIEW

**Review by dennisseah — APPROVED** [review]

**Review by bnookala — APPROVED** [review]

**Review by mtarng — COMMENTED** [review]
Any documentation changes needed to go along with this?

**Comment by samiyaakhtar** [comment]
@mtarng not that i can find a doc to update. @dennisseah is there a file I missed updating that generates command documentation?

**Comment by mtarng** [comment]
No, the decorator files are used for the docs generation. I'm just making sure there aren't any walkthrough type documentation that needs updating,

**Review by mtarng — APPROVED** [review]

**Comment by samiyaakhtar** [comment]
@mtarng don't think any walkthrough docs have it. Will merge

**Pull request merged**
