### PR TITLE
[FEATURE] have error code for deployment get command

### LINKED ISSUE #1316: Have specific error codes and error chain for deployment get command
**As a:**
User

**I want:**
error specific codes and error chaining for deployment get command

**So that:**
I can understand the root cause.

**Describe the solution you'd like:**
add error code and maintain exception chain

**Acceptance Criteria:**

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**
No

part of https://github.com/microsoft/bedrock/issues/1088

### PR DESCRIPTION
**Pull request by dennisseah**
1. converted all errors to cascading error with error id
2. fix some jest tests
3. use async-await instead of then, catch

ran integration test successfully

closes https://github.com/microsoft/bedrock/issues/1316

### CODE REVIEW

**Comment by samiyaakhtar** [comment]
Seeing a regression when i run against this branch: 
Screen Shot 2020-04-06 at 11 18 21 AM

**Comment by dennisseah** [comment]
> Seeing a regression when i run against this branch:
> Screen Shot 2020-04-06 at 11 18 21 AM

i will test again. does this happens only for -wide?

**Comment by samiyaakhtar** [comment]
@dennisseah yes

**Comment by dennisseah** [comment]
> > Seeing a regression when i run against this branch:
> > Screen Shot 2020-04-06 at 11 18 21 AM
> 
> i will test again. does this happens only for -wide?

it is also happening for master branch because here https://github.com/CatalystCode/spk/blob/master/src/commands/deployment/get.ts#L244, we have .then and do not have .catch. I will try to fix this. I guess we print warning if we cannot fetch PR, please confirm

**Comment by samiyaakhtar** [comment]
@dennisseah interesting, didn't see it happen on master for me but maybe i need to pull again.

**Comment by samiyaakhtar** [comment]
@dennisseah i just pulled the latest and it's working on master. Maybe we need to have promise and resolve? 
Screen Shot 2020-04-06 at 11 52 02 AM

**Review by edaena — APPROVED** [review]
Looks good. Just verify the functionality by running the integration tests before merging.

**Review by samiyaakhtar — APPROVED** [review]
Works with `-o wide` now. Thanks @dennisseah

**Pull request merged**
