### PR TITLE
[REFACTOR] HLD pipeline command

### PR DESCRIPTION
**Pull request by dennisseah**
Related to https://github.com/microsoft/bedrock/issues/885
1. move command declaration to a JSON file
2. standardized on the function in command ts file
3. use the CommandBuilder's exit function
4. still default value of command option values is set to "" and values fall back to values in config file, typeof optionValue === "string" is not needed.
5. added more tests

### CODE REVIEW

**Review by andrebriggs — COMMENTED** [review]
Thanks @dennisseah. This looks in line with the other refactoring. Does the integration test pass with these changes?

**Comment by dennisseah** [comment]
> Thanks @dennisseah. This looks in line with the other refactoring. Does the integration test pass with these changes?

Yes, I will run it again as i just did a rebase.

**Comment by dennisseah** [comment]
> > Thanks @dennisseah. This looks in line with the other refactoring. Does the integration test pass with these changes?
> 
> Yes, I will run it again as i just did a rebase.

it is good
```
Successfully reached the end of the validations scripts.
```

**Review by andrebriggs — APPROVED** [review]
Approved pending any integration test re-runs from further commits @dennisseah

**Review by samiyaakhtar — APPROVED** [review]

**Comment by dennisseah** [comment]
ran sh validations.sh successful. Merging this PR. Thanks

**Pull request merged**
