### PR TITLE
Create unique tables in the onboard test

### LINKED ISSUE #1101: Introspection smoke test is failing intermittently due to az cli timeout
**Describe the bug:**
Introspection test is testing the onboard command which creates a table in a storage. Then the test tries to delete the table and az cli times out even after increasing the timeout from 50s to 120s. The test should not depend on whether az cli is successful or not. We should use a different cleanup mechanism.

Also consider removing this test.

**To Reproduce:**
Failures of [this kind](https://dev.azure.com/epicstuff/bedrock/_build/results?buildId=13489&view=logs&j=75b9d1eb-f58e-5019-295a-7684b5b743da&t=06321f81-91d7-59ce-8241-0a1a98595180&l=53)

**Expected behavior:**
It should pass whether or not az cli delete passes.

**Screenshots:**
Screen Shot 2020-03-05 at 1 57 02 PM

**Additional context:**

- [x] Change the test to create a storage account with a different name

- [x] Setup a separate test cleaning mechanism to clean all the test storage accounts

**Does this require updates to documentation?:**

### PR DESCRIPTION
**Pull request by edaena**
Closes [Bedrock #1101](https://github.com/microsoft/bedrock/issues/1101)

### CODE REVIEW

**Review by sarath-p — APPROVED** [review]

**Review by dennisseah — APPROVED** [review]

**Comment by andrebriggs** [comment]
> Setup a separate test cleaning mechanism to clean all the test storage accounts

@edaena maybe I missed something but where does the above happen? We shouldn't close unless https://github.com/microsoft/bedrock/issues/1101 is done

**Comment by edaena** [comment]
@dennisseah Just added the template for the logic app.

**Comment by edaena** [comment]
@andrebriggs I added the template for the logic app that does the cleanup.

**Review by andrebriggs — APPROVED** [review]
LGTM

**Pull request merged**
