### PR TITLE
rename docs folder to documentations

### PR DESCRIPTION
**Pull request by dennisseah**
related to https://github.com/microsoft/bedrock/issues/976

### CODE REVIEW

**Comment by mtarng** [comment]
Why do we need to rename the folder? Also `documentation` should be fine for plural form.

**Comment by dennisseah** [comment]
> Why do we need to rename the folder? Also `documentation` should be fine for plural form.

This is mentioned in Slack #spk yesterday and we have 24 hours for people to read this https://github.com/microsoft/bedrock/issues/976. I am renaming `docs` -> `documentations` both are plural. Please let me know your concern. thanks

**Comment by mtarng** [comment]
Looks like this is breaking a few image and relative links within our docs too. 

spk diagram: https://github.com/CatalystCode/spk/blob/mvDos/README.md
First link under: https://github.com/CatalystCode/spk/tree/mvDos#getting-started
spk resources diagram right above link: https://github.com/CatalystCode/spk/blob/mvDos/documentations/project-service-management-guide.md#requirements

There might be a few others too.

**Comment by dennisseah** [comment]
> Looks like this is breaking a few image and relative links within our docs too.
> 
> spk diagram: https://github.com/CatalystCode/spk/blob/mvDos/README.md
> First link under: https://github.com/CatalystCode/spk/tree/mvDos#getting-started
> spk resources diagram right above link: https://github.com/CatalystCode/spk/blob/mvDos/documentations/project-service-management-guide.md#requirements
> 
> There might be a few others too.

Thanks. I will fix them

**Comment by evanlouie** [comment]
`docs` is the primary standard for most of our repositories as well as most msft repos. We should keep with `docs`

**Comment by dennisseah** [comment]
> `docs` is the primary standard for most of our repositories as well as most msft repos. We should keep with `docs`

`docs` is used as a folder for serving out web content from git pages. hence we need to move it. git pages does not allow us to change the folder name for web content.

**Comment by andrebriggs** [comment]
I propose we have `docs` for the GitHub Pages stuff and perhaps `guides` for the markdown documentation we have

**Comment by dennisseah** [comment]
> I propose we have `docs` for the GitHub Pages stuff and perhaps `guides` for the markdown documentation we have

I have not problem with this

**Review by andrebriggs — APPROVED** [review]
LGTM

**Comment by dennisseah** [comment]
@mtarng and @evanlouie, please let me know if this changes are ok with you. And can you please approve it so I can move forward. thanks

**Review by mtarng — APPROVED** [review]

**Comment by dennisseah** [comment]
@andrebriggs am I allowed to merge this one. Tests are failing for different reasons.

**Comment by andrebriggs** [comment]
@dennisseah yes, let's merge

**Pull request merged**
