### PR TITLE
Fixing bug where multi-state pipeline status was showing up incorrectly

### LINKED ISSUE #1210: spk deployment get returns the wrong status for ACR to HLD multi-stage pipelines
**Describe the bug:**
The result is wrong when multi stage pipelines are used instead of traditional Azure releases

**To Reproduce:**
Run init on any configuration that uses multi-stage pipelines

**Expected behavior:**
Result should show passed

**Screenshots:**
Screen Shot 2020-03-20 at 3 52 22 PM

**Additional context:**

**Does this require updates to documentation?:**

### PR DESCRIPTION
**Pull request by samiyaakhtar**
Closes https://github.com/microsoft/bedrock/issues/1210

### CODE REVIEW

**Comment by andrebriggs** [comment]
@samiyaakhtar we don't seem to test the HLD to Manifest column data: https://github.com/CatalystCode/spk/blob/bf01091aa101eb7e7a2cba8d184a99e31c947be1/tests/validations.sh#L430 Is this tested elsewhere?

**Comment by andrebriggs** [comment]
> @samiyaakhtar we don't seem to test the HLD to Manifest column data:
> 
> https://github.com/CatalystCode/spk/blob/bf01091aa101eb7e7a2cba8d184a99e31c947be1/tests/validations.sh#L430
> 
> Is this tested elsewhere?

I see it now in another PR. @samiyaakhtar I raised https://github.com/microsoft/bedrock/issues/912 to hi pri. Let's bubble these things up.

**Comment by samiyaakhtar** [comment]
@andrebriggs it's being tested in this PR https://github.com/CatalystCode/spk/pull/429/files

**Comment by samiyaakhtar** [comment]
> @samiyaakhtar I raised microsoft/bedrock#912 to hi pri. Let's bubble these things up.

@andrebriggs Implemented a temporary workaround for it until 912 is fixed

**Review by andrebriggs — APPROVED** [review]

**Review by yradsmikham — APPROVED** [review]

**Pull request merged**
