### PR TITLE
Resource based commands

### PR DESCRIPTION
**Pull request by evanlouie**
- Added a custom command dispatcher. This dispatcher allow for arbitrarily nested Command objects; enabling resource based commands.
- Moved the `init` command under `project`; now it is called via `spk project init` (a la resource based commands)

### CODE REVIEW

**Review by andrebriggs — COMMENTED** [review]
@evanlouie what else can a `project` action do? Is there any roadmap on this potential other commands? Just want to make sure we aren't getting too concrete too fast

**Comment by andrebriggs** [comment]
@evanlouie why is there an "examples" directory?

**Review by bnookala — APPROVED** [review]

**Comment by evanlouie** [comment]
@andrebriggs No roadmap really. This refactor came out some discussions had during the code walk through yesterday. It was brought up by multiple people that we should really support resource based commands (a la azcli); which is something we previously couldn't do in the code setup. I moved the `init` function primarily to give an example of how creating nested sub-commands looks in this setup.

**Review by jmspring — APPROVED** [review]
In general, LGTM.  The refactoring to support resource based commands limits us to basically - "resource" "command" - rather than variable depth.  I believe this is fine for our project at the moment, but should be revisited if more flexibility is needed.

**Comment by andrebriggs** [comment]
> @andrebriggs No roadmap really. This refactor came out some discussions had during the code walk through yesterday. It was brought up by multiple people that we should really support resource based commands (a la azcli); which is something we previously couldn't do in the code setup. I moved the `init` function primarily to give an example of how creating nested sub-commands looks in this setup.

Agreed on the resource based commands. Thanks for clarifying the nested sub-command

**Review by andrebriggs — APPROVED** [review]

**Pull request merged**
