### PR TITLE
Fix Issue 902: Values from Leaf node is not copied over

### PR DESCRIPTION
**Pull request by dennisseah**
reimplement dirIteration function to take all values from leaf node. add more checks on the functions.

successfully ran validations.sh

### CODE REVIEW

**Comment by yradsmikham** [comment]
@dennisseah the infra integration tests are in `infra-validations.sh`. Were you able to run this successfully?

**Comment by yradsmikham** [comment]
@dennisseah tested this locally, along with unit tests, and it appears the bug is fixed. Will approve once integration tests are confirmed.

**Comment by dennisseah** [comment]
> @dennisseah tested this locally, along with unit tests, and it appears the bug is fixed. Will approve once integration tests are confirmed.

yes
```
TEST_WORKSPACE: /Users/veseah/forks/spk/tests/spk-env
SPK_LOCATION: /Users/veseah/bin/spk
AZDO_PROJECT: BedrockSPK
AZDO_ORG: veseah
AZDO_ORG_URL: https://dev.azure.com/veseah
ACR_NAME: bedrockSPK
SPK Version: 0.3.0
Running from /Users/veseah/forks/spk/tests
Directory '/Users/veseah/forks/spk/tests/spk-env' does not exist
Created '/Users/veseah/forks/spk/tests/spk-env'
Initialized empty Git repository in /Users/veseah/forks/spk/tests/spk-env/discovery-tf-template/.git/
The remote_repo_url is https://veseah@dev.azure.com/veseah/BedrockSPK/_git/discovery-tf-template
[master (root-commit) 96b08bd] inital commit
 3 files changed, 11 insertions(+)
 create mode 100644 template/backend.tfvars
 create mode 100644 template/main.tf
 create mode 100644 template/variables.tf
git push
Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (6/6), 518 bytes | 518.00 KiB/s, done.
Total 6 (delta 0), reused 0 (delta 0)
remote: Analyzing objects... (6/6) (6 ms)
remote: Storing packfile... done (270 ms)
remote: Storing index... done (71 ms)
To https://dev.azure.com/veseah/BedrockSPK/_git/discovery-tf-template
 * [new branch]      master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.
Total 0 (delta 0), reused 0 (delta 0)
To https://dev.azure.com/veseah/BedrockSPK/_git/discovery-tf-template
 * [new tag]         v0.0.1 -> v0.0.1
/Users/veseah/forks/spk/tests/spk-env
../discovery-tf-template
v0.0.1
Checking directory /Users/veseah/forks/spk/tests/spk-env/discovery-infra-hld
Current file: /Users/veseah/forks/spk/tests/spk-env/discovery-infra-hld/definition.yaml
warn:    No project folder was provided, spk will generate the current folder as a project
warn:    A definition.yaml was found in: /Users/veseah/forks/spk/tests/spk-env/discovery-infra-hld, and was found in /Users/veseah/forks/spk/tests/spk-env/discovery-infra-hld
info:    Checking for locally stored template: template from remote repository: https://dev.azure.com/veseah/BedrockSPK/_git/discovery-tf-template at version: v0.0.1
warn:    Converted to: _veseah_bedrockspk__git_discovery_tf_template
info:    Checking if source: /Users/veseah/.spk/templates/_veseah_bedrockspk__git_discovery_tf_template is stored locally.
info:    Source template folder found. Validating existence of repository.
info:    Remote source repo: https://dev.azure.com/veseah/BedrockSPK/_git/discovery-tf-template exists.
info:    Checking if source repo: https://dev.azure.com/veseah/BedrockSPK/_git/discovery-tf-template has been already cloned to: /Users/veseah/.spk/templates/_veseah_bedrockspk__git_discovery_tf_template.
info:    https://dev.azure.com/veseah/BedrockSPK/_git/discovery-tf-template already cloned. Performing 'git pull'...
info:    Checking out template version: v0.0.1
info:    Created generated directory: /Users/veseah/forks/spk/tests/spk-env/discovery-infra-hld-generated
info:    Terraform template files copied from /Users/veseah/.spk/templates/_veseah_bedrockspk__git_discovery_tf_template/template
Checking directory /Users/veseah/forks/spk/tests/spk-env/discovery-infra-hld-generated
Current file: /Users/veseah/forks/spk/tests/spk-env/discovery-infra-hld-generated/spk.tfvars
Current file: /Users/veseah/forks/spk/tests/spk-env/discovery-infra-hld-generated/main.tf
Current file: /Users/veseah/forks/spk/tests/spk-env/discovery-infra-hld-generated/backend.tfvars
Current file: /Users/veseah/forks/spk/tests/spk-env/discovery-infra-hld-generated/variables.tf
Validatng file /Users/veseah/forks/spk/tests/spk-env/discovery-infra-hld-generated/spk.tfvars
File contents have been successfully validated in /Users/veseah/forks/spk/tests/spk-env/discovery-infra-hld-generated/spk.tfvars
Validatng file /Users/veseah/forks/spk/tests/spk-env/discovery-infra-hld-generated/backend.tfvars
File contents have been successfully validated in /Users/veseah/forks/spk/tests/spk-env/discovery-infra-hld-generated/backend.tfvars
```

**Review by yradsmikham — APPROVED** [review]

**Review by andrebriggs — APPROVED** [review]

**Comment by dennisseah** [comment]
closes https://github.com/microsoft/bedrock/issues/902

**Pull request merged**
