### PR TITLE
Add support for backend config in `spk infra scaffold`

### LINKED ISSUE #722: Clean up HCL generation in `spk infra scaffold`
**As a:**
Developer  

**I want:**
remove HCL generation in `spk infra scaffold`

**So that:**
there aren't unused arguments or functionalities

**Describe the solution you'd like:**
- [x] remove `--hcl` argument

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**
Yes

### PR DESCRIPTION
**Pull request by yradsmikham**
Closes https://github.com/microsoft/bedrock/issues/722 and https://github.com/microsoft/bedrock/issues/727.

### CODE REVIEW

**Review by edaena — APPROVED** [review]

**Comment by andrebriggs** [comment]
@yradsmikham look good business logic wise. What is the plan to get the [coverage](https://dev.azure.com/epicstuff/bedrock/_build/results?buildId=7030&view=codecoverage-tab) greater than 44%?

**Comment by yradsmikham** [comment]
@andrebriggs, we are definitely keeping an eye on line and branch coverage while writing tests, and the hope is that scaffold would expand a little more in the coming sprints, which implies more unit testing. 

If you look at the code coverage [breakdown](https://dev.azure.com/epicstuff/bedrock/_build/results?buildId=7030&view=codecoverage-tab), you'll find that the reason why code coverage is "low" is because a lot of the code written for scaffold is reliant on file system (fs). There's certainly no issue with writing "mocks" for code that interacts with file system, but that starts to bridge the conversation around writing integration tests versus unit tests.

I find that code coverage statistics are something to consider when writing code, but does not _always_ give an accurate depiction of code quality.

**Review by jmspring — APPROVED** [review]
Lgtm

**Review by NathanielRose — APPROVED** [review]
Running int a small thing where .backip still continues to get appended on an existing directory I am scaffolding. Not sure how we want to handle this in the future or note as a quick bug:

```
    Directory: C:\Users\naros\Desktop\Microsoft\fy20\spk\spk-infra\spk\discovery-service


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       10/29/2019  11:14 AM           1137 definition.json
-a----       10/29/2019  10:45 AM           2033 main.tf
-a----       10/29/2019  10:45 AM            698 README.md
-a----       10/29/2019  10:45 AM            795 terraform.tfvars.backup.backup.backup
-a----       10/29/2019  10:45 AM           2670 variables.tf
```

**Comment by yradsmikham** [comment]
> Running int a small thing where .backip still continues to get appended on an existing directory I am scaffolding. Not sure how we want to handle this in the future or note as a quick bug:
> 
> ```
>     Directory: C:\Users\naros\Desktop\Microsoft\fy20\spk\spk-infra\spk\discovery-service
> 
> 
> Mode                LastWriteTime         Length Name
> ----                -------------         ------ ----
> -a----       10/29/2019  11:14 AM           1137 definition.json
> -a----       10/29/2019  10:45 AM           2033 main.tf
> -a----       10/29/2019  10:45 AM            698 README.md
> -a----       10/29/2019  10:45 AM            795 terraform.tfvars.backup.backup.backup
> -a----       10/29/2019  10:45 AM           2670 variables.tf
> ```

This is resolved in this PR now :)

**Pull request merged**
