### PR TITLE
[DOC-FIX] remove CORS setting requirement

### PR DESCRIPTION
**Pull request by dennisseah**

### CODE REVIEW

**Comment by edaena** [comment]
@dennisseah Why is this requirement removed?

**Comment by dennisseah** [comment]
> @dennisseah Why is this requirement removed?

We implemented the backend for dashboard and CORS settings are not needed. @samiyaakhtar can you confirm. Generally setting CORS for localhost is not good things (w.r.t. security)

**Comment by samiyaakhtar** [comment]
@dennisseah @edaena shouldn't be needed anymore if people are using the new docker image hopefully, that queries APIs from a backend instead. I guess we can remove it since we've already updated the image

**Review by samiyaakhtar — APPROVED** [review]

**Comment by edaena** [comment]
@samiyaakhtar @dennisseah do we need to also remove enabling CORS in the storage account in the integration tests?

**Review by andrebriggs — APPROVED** [review]

**Comment by samiyaakhtar** [comment]
@edaena Agreed, maybe we should get rid of that snippet of code from integration tests as well. Might be worth closing out in one PR. @dennisseah could we remove the part from rings integration test which adds CORS setting to the storage account?

**Comment by dennisseah** [comment]
> @edaena Agreed, maybe we should get rid of that snippet of code from integration tests as well. Might be worth closing out in one PR. @dennisseah could we remove the part from rings integration test which adds CORS setting to the storage account?

can someone do it? or tell me where is it if you want me to remove it :-)

**Comment by samiyaakhtar** [comment]
@dennisseah it had to be done before the PR was merged :( I'll open another PR for this.

**Pull request merged**
