### PR TITLE
Adding basic unit tests for `deployment`

### PR DESCRIPTION
**Pull request by samiyaakhtar**

### CODE REVIEW

**Review by evanlouie — APPROVED** [review]
Yay for test mocks 👍

**Review by sarath-p — APPROVED** [review]
Looks good

**Review by edaena — APPROVED** [review]

**Comment by samiyaakhtar** [comment]
Related to https://github.com/microsoft/bedrock/issues/599

**Comment by andrebriggs** [comment]
@samiyaakhtar let's include negative test cases as well.

**Comment by samiyaakhtar** [comment]
@andrebriggs will do

**Pull request merged**
