### PR TITLE
[REFACTOR] project init command

### PR DESCRIPTION
**Pull request by dennisseah**
1. have command decoration to a separation JSON file
2. improve test coverage from 60 to 80%.
3. create helper functions for creating random dir
4. create helper functions for checking if file exists
5. remove unused function (ls) in init.ts
6. proper exit code for init.ts
7. make reduce function in init.ts more readable

successfully ran validations.sh 

Related to https://github.com/microsoft/bedrock/issues/885

### CODE REVIEW

**Review by andrebriggs — APPROVED** [review]

**Comment by andrebriggs** [comment]
@sarath-p @mtarng

**Review by sarath-p — APPROVED** [review]
Looks good.

**Comment by mtarng** [comment]
Do you think `src/lib/ioUtil.ts` would only be used to unit tests? If so, could we move it under `src/test/ioUtil.ts`? @dennisseah

**Comment by dennisseah** [comment]
> Do you think `src/lib/ioUtil.ts` would only be used to unit tests? If so, could we move it under `src/test/ioUtil.ts`? @dennisseah

I hope to not restrict it to tests. Thanks

**Review by mtarng — APPROVED** [review]

**Pull request merged**
