### PR TITLE
Fixing the noop broken project lifecycle pipeline

### LINKED ISSUE #899: [spk] Pipelines need to include Buildscript url as a pipeline, also fix option for passing in build script url
**Describe the bug:**
Project lifecycle pipeline is NOOP right now due to the missing pipeline variable for downloading a `build.sh`
**To Reproduce:**
run the smoke tests

**Expected behavior:**
smoke tests should pass

**Screenshots:**

**Additional context:**

**Does this require updates to documentation?:**

### PR DESCRIPTION
**Pull request by mtarng**
Closes https://github.com/microsoft/bedrock/issues/899

### CODE REVIEW

**Review by bnookala — APPROVED** [review]

**Review by evanlouie — APPROVED** [review]

**Review by sarath-p — APPROVED** [review]
LGTM

**Review by dennisseah — APPROVED** [review]
👍

**Comment by andrebriggs** [comment]
Looks good. @mtarng I assume you tested locally? Also why are we removing the `hld repo url`?

**Review by andrebriggs — APPROVED** [review]

**Comment by mtarng** [comment]
@andrebriggs hld repo url is now configured in the variable group for the project.

**Comment by mtarng** [comment]
Adding minor change. Apparently isValidConfig was never being used to check for service pipelines. There exists unit tests for it already.

**Review by sarath-p — APPROVED** [review]

**Pull request merged**
